plugins {
    // Loaded once here so all the subprojects share them. The versions are in gradle.properties
    id 'net.fabricmc.fabric-loom' version "${loom_version}" apply false
    id 'net.neoforged.moddev' version "${moddev_version}" apply false

    // ModDevGradle makes the IntelliJ run configurations with this plugin, but brings the old version 1.2.
    // 1.4.1 fixes its "DomainObjectCollection.findAll(Closure) method has been deprecated" warning
    id 'org.jetbrains.gradle.plugin.idea-ext' version '1.4.1' apply false
}